// User types
export type UserRole = 'maintenance' | 'operations';

export interface User {
  id: string;
  name: string;
  role: UserRole;
  email: string;
  garageId?: string; // Optional: assigned garage
}

// Garage types
export type GarageLocation = 'North' | 'South';

export interface Garage {
  id: string;
  name: string;
  location: GarageLocation;
  capacity: number;
  address: string;
  coordinates: {
    lat: number;
    lng: number;
  };
}

// Bus types
export type BusStatus = 'active' | 'decommissioned' | 'maintenance';
export type BusType = 'Standard' | 'Articulated' | 'Double-Decker' | 'Mini';

export interface Bus {
  id: string; // e.g., "bus-001"
  vehicleNumber: string; // e.g., "TL-N-001"
  type: BusType;
  capacity: number;
  status: BusStatus;
  estimatedActiveDate?: string; // For decommissioned or maintenance status
  garageId: string;
  currentMileage: number;
  registrationDate: string;
  lastMaintenanceDate: string;
  components: Component[];
  additionalMaintenanceItems?: AdditionalMaintenanceItem[]; // Custom maintenance items
  coordinates?: {
    lat: number;
    lng: number;
  };
}

// Component types
export type ComponentType =
  | 'tire_fl' | 'tire_fr' | 'tire_rl' | 'tire_rr'
  | 'brake_pad_fl' | 'brake_pad_fr' | 'brake_pad_rl' | 'brake_pad_rr'
  | 'rotor_fl' | 'rotor_fr' | 'rotor_rl' | 'rotor_rr'
  | 'engine' | 'suspension' | 'transmission' | 'battery'
  | 'air_conditioning' | 'alternator'
  | 'other'; // For custom components in "Other" category

export type ComponentPosition = 'FL' | 'FR' | 'RL' | 'RR' | 'N/A';
export type ComponentStatus = 'good' | 'warning' | 'critical' | 'overdue';

export interface Component {
  id: string;
  type: ComponentType;
  name?: string; // Custom name for 'other' type components
  position: ComponentPosition;
  installedDate: string;
  lifetimeKm: number; // Expected lifetime in kilometers
  renewalDate: string; // Calculated renewal date
  estimatedCost: number;
  costOverride?: number; // Override for actual cost
  currentMileage: number; // Mileage when installed
  status: ComponentStatus;
}

// Additional Maintenance Items (text-based, fully editable)
export interface AdditionalMaintenanceItem {
  id: string;
  description: string; // Text description of the maintenance item
  installedDate: string; // Editable
  renewalDate: string; // Editable
  cost: number; // Editable
  status: ComponentStatus;
  notes?: string;
}

export interface ComponentMaster {
  type: ComponentType;
  displayName: string;
  category: 'Tires' | 'Brakes' | 'Engine' | 'Other';
  defaultLifetimeKm: number;
  averageCost: number;
  requiresPosition: boolean;
}

// Work Order types
export type WorkOrderStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled';
export type WorkOrderPriority = 'low' | 'medium' | 'high' | 'critical';

export interface WorkOrder {
  id: string;
  busId: string;
  garageId: string;
  title: string;
  description: string;
  components: ComponentType[]; // Components to be replaced/repaired
  priority: WorkOrderPriority;
  status: WorkOrderStatus;
  assignedMechanic?: string;
  createdDate: string;
  scheduledDate?: string;
  completedDate?: string;
  estimatedCost: number;
  actualCost?: number;
  notes: string;
  isAutoGenerated: boolean; // True if generated by system
  maintenanceItemId?: string; // Link to additional maintenance item if applicable
}

// Maintenance History
export interface MaintenanceHistory {
  id: string;
  busId: string;
  workOrderId: string;
  componentType: ComponentType;
  action: 'replaced' | 'repaired' | 'inspected';
  date: string;
  cost: number;
  mechanicName: string;
  notes: string;
}

// Maintenance Alert
export interface MaintenanceAlert {
  id: string;
  busId: string;
  vehicleNumber: string;
  componentType: ComponentType;
  componentPosition: ComponentPosition;
  status: ComponentStatus;
  mileageOverdue: number;
  estimatedCost: number;
  priority: WorkOrderPriority;
}
